### PR TITLE
Docs and command help improvements

### PR DESCRIPTION
**Pull request by tsibley**
A bunch of cumulative improvements to how we handle docs and command help. See commits for details, naturally.

### Testing

- [x] Preview looks good
- [x] `--help` output for various commands looks good
- [ ] Checks pass

### CODE REVIEW

**Review by jameshadfield — COMMENTED** [review]
Had this on my to-do list thinking it was the runtime docs updates, which it's not... but for what it's worth I skimmed through each commit and these changes all seem fine to me. It'd still be great to have argparse rST parsing in augur, but I realise that's a whole nother push.

**Comment by tsibley** [comment]
Ha, yeah. It's on the (twisty) path to those… things I decided to fix/improve as I noticed them as part of making those runtime docs.

If we want to have a big focused doc push on Augur, we could definitely port/extract the argparse/rST stuff...

**Comment by tsibley** [comment]
There were a series of small issues revealed by CI that I hadn't anticipated, so good for CI I guess! I believe with the last push just now that CI should pass and this should be good to go.

**Comment by tsibley** [comment]
[CI passed](https://github.com/nextstrain/cli/actions/runs/5616274947) for the commit before the changelog commit. [Doc preview](https://nextstrain--299.org.readthedocs.build/projects/cli/en/299/) looks good. I'm going to merge given @jameshadfield's 👀 on most of this already but welcome additional review! I don't expect to cut a new release until after some other doc updates/additions are made for runtimes.

**Comment by joverlee521** [comment]
Nice overall improvements! I really like that the addition of direct links to command line arguments. 

My only suggestion is add a blurb that explicitly states that command line doc changes need to be manually updated via `./devel/generate-command-doc` and checked into version control. I think this would fit in the development.md docs or maybe as a hint in the `tests/doc.py` error message?

**Comment by tsibley** [comment]
Ah, that's fair. Done in https://github.com/nextstrain/cli/commit/e2420d4f0abf7a9c7f451411239753bd8bde9cc5!

**Pull request merged**
