### PR TITLE
Mention Singularity in a few more lists of runtimes that occur in help and docs

### PR DESCRIPTION
**Pull request by tsibley**
Good to be consistent when enumerating our runtimes, even if a couple of the lists in context suggest they're non-exhaustive.

## Checklist

- [x] Checks pass

### CODE REVIEW

**Comment by victorlin** [comment]
Is it also worth mentioning on the main docs [install page](https://docs.nextstrain.org/en/latest/install.html)? Example:

image

**Comment by tsibley** [comment]
Probably!

**Comment by j23414** [comment]
[non-blocking comment]

Despite the [rebranding of "Singularity" to "Apptainer,"](https://apptainer.org/) I assume that the majority of users are still more acquainted with the name "Singularity."

**Comment by victorlin** [comment]
@j23414 If you have access to any HPC systems, do you know if `singularity` or `apptainer` (or both) are available as commands?

**Comment by j23414** [comment]
I have access to 2 HPCs, so some but limited experience.  

For one, both are available where 
> the `singularity` command is just a symlink to `apptainer`

The other seems to maintain a separate `apptainer` module: https://sciwiki.fredhutch.org/compdemos/Apptainer/

Notably, my previous pipelines dependent on Singularity are now generating various migration warnings, such as advising the use of 'APPTAINER_CACHEDIR' instead of 'SINGULARITY_CACHEDIR.' which people msg/email me about 😆

**Comment by j23414** [comment]
In summary, I think it's safe to use the term "singularity" or "Apptainer (was singularity)".

**Comment by tsibley** [comment]
Yeah, the [Singularity runtime documentation](https://docs.nextstrain.org/projects/cli/en/stable/runtimes/singularity/?highlight=Apptainer) page discusses Singularity vs. Apptainer and compatibility.

**Pull request merged**
